Repository tmax-cloud/MSA-payment, pull requests merged in 2021-12, with the labels that each got.

#2 [feat] Add cicd config
  payment-integration-config.yaml
Labels: size/M

#3 [feat] add swagger api
  .gitignore
  HELP.md
  README.md
  payment.iml
  src/main/java/com/example/payment/config/SwaggerConfig.java
  src/main/java/com/example/payment/config/SwaggerConfiguration.java
  target/classes/application.yaml
  target/classes/com/example/payment/PaymentApplication.class
  target/classes/com/example/payment/controller/PaymentController.class
  target/classes/com/example/payment/model/Payment.class
  target/classes/com/example/payment/repo/PaymentRepo.class
  target/maven-archiver/pom.properties
  target/maven-status/maven-compiler-plugin/compile/default-compile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/compile/default-compile/inputFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/createdFiles.lst
  target/maven-status/maven-compiler-plugin/testCompile/default-testCompile/inputFiles.lst
  target/payment-0.0.1-SNAPSHOT.jar.original
Labels: size/L

#4 [fix]n fix cicd config
  payment-integration-config.yaml
Labels: size/XS

#5 [fix] fix payment cicd config
  payment-integration-config.yaml
Labels: size/S
